version: '3'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - DATABASE_URL=mysql://root:miqi@1109.com@db:3306/db_name
      # 替换为您的数据库连接信息
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: miqi@1109.com
      MYSQL_DATABASE: order_manage
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
