version: '3'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql

  mysql:
    image: mysql:lastest
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=miqi@1109.com
      - MYSQL_DATABASE=order-manage
#      - MYSQL_USER=root
      - MYSQL_PASSWORD=miqi@1109.com
    ports:
      - 3306:3306

